// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBti4972lUiZrZILsNJoOecfSRG5SfVdac',
    appId: '1:28531651093:web:5a0ed5258152f3fbd1141c',
    messagingSenderId: '28531651093',
    projectId: 'barber-club-fr-123',
    authDomain: 'barber-club-fr-123.firebaseapp.com',
    storageBucket: 'barber-club-fr-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpF8HGTBMjexuSNELRO83K2iq5h9iqntw',
    appId: '1:28531651093:android:db9f65a500eeeb88d1141c',
    messagingSenderId: '28531651093',
    projectId: 'barber-club-fr-123',
    storageBucket: 'barber-club-fr-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCShkM4uFJe95-addraX8LmIHp8QYI-ulM',
    appId: '1:28531651093:ios:b255e659a2116324d1141c',
    messagingSenderId: '28531651093',
    projectId: 'barber-club-fr-123',
    storageBucket: 'barber-club-fr-123.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCShkM4uFJe95-addraX8LmIHp8QYI-ulM',
    appId: '1:28531651093:ios:b255e659a2116324d1141c',
    messagingSenderId: '28531651093',
    projectId: 'barber-club-fr-123',
    storageBucket: 'barber-club-fr-123.firebasestorage.app',
    iosBundleId: 'com.example.barber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBti4972lUiZrZILsNJoOecfSRG5SfVdac',
    appId: '1:28531651093:web:91981c11935996a1d1141c',
    messagingSenderId: '28531651093',
    projectId: 'barber-club-fr-123',
    authDomain: 'barber-club-fr-123.firebaseapp.com',
    storageBucket: 'barber-club-fr-123.firebasestorage.app',
  );
}
